version: '2.0'
services:
    ca.AdminTeam.liquor.com:
        image: 'hyperledger/fabric-ca:1.4.3'
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-AdminTeam
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.AdminTeam.liquor.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/af4c16d3dfc2bf28cd87b44f48af425d8a41f9b18f254bbc85691273ea950eb1_sk
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.AdminTeam.liquor.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/af4c16d3dfc2bf28cd87b44f48af425d8a41f9b18f254bbc85691273ea950eb1_sk
        ports:
            - '7054:7054'
        command: 'sh -c ''fabric-ca-server start -b admin:adminpw -d'''
        volumes:
            - './crypto-config/peerOrganizations/AdminTeam.liquor.com/ca/:/etc/hyperledger/fabric-ca-server-config'
        container_name: ca_peerAdminTeam
    ca.Manufacturer.liquor.com:
        image: 'hyperledger/fabric-ca:1.4.3'
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-Manufacturer
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Manufacturer.liquor.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/36ad09f2e8e6e4f631cf9d3d9556647c8b2673a81e1d15b3b903d9a2ff88bbb8_sk
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Manufacturer.liquor.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/36ad09f2e8e6e4f631cf9d3d9556647c8b2673a81e1d15b3b903d9a2ff88bbb8_sk
        ports:
            - '7154:7054'
        command: 'sh -c ''fabric-ca-server start -b admin:adminpw -d'''
        volumes:
            - './crypto-config/peerOrganizations/Manufacturer.liquor.com/ca/:/etc/hyperledger/fabric-ca-server-config'
        container_name: ca_peerManufacturer
    
    orderer.liquor.com:
        container_name: orderer.liquor.com
        image: 'hyperledger/fabric-orderer:1.4.3'
        environment:
            - ORDERER_GENERAL_LOGLEVEL=debug
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt           
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerAdminTeam/tls/ca.crt, /etc/hyperledger/crypto/peerManufacturer/tls/ca.crt]
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
        command: orderer
        ports:
            - '7050:7050'
        volumes:
            - '../artifacts:/etc/hyperledger/configtx'
            - './crypto-config/ordererOrganizations/liquor.com/orderers/orderer.liquor.com/:/etc/hyperledger/crypto/orderer'
            - './crypto-config/peerOrganizations/AdminTeam.liquor.com/peers/peer0.AdminTeam.liquor.com/:/etc/hyperledger/crypto/peerAdminTeam'
            - './crypto-config/peerOrganizations/Manufacturer.liquor.com/peers/peer0.Manufacturer.liquor.com/:/etc/hyperledger/crypto/peerManufacturer'
            
#            - './orderer.liquor.com:/var/hyperledger/production/orderer'

    orderer1.liquor.com:
        container_name: orderer1.liquor.com
        image: 'hyperledger/fabric-orderer:1.4.3'
        environment:
            - ORDERER_GENERAL_LOGLEVEL=debug
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerAdminTeam/tls/ca.crt, /etc/hyperledger/crypto/peerManufacturer/tls/ca.crt]          
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
        command: orderer
        ports:
            - '8050:7050'
        volumes:
            - '../artifacts:/etc/hyperledger/configtx'
            - './crypto-config/ordererOrganizations/liquor.com/orderers/orderer1.liquor.com/:/etc/hyperledger/crypto/orderer'
            - './crypto-config/peerOrganizations/AdminTeam.liquor.com/peers/peer0.AdminTeam.liquor.com/:/etc/hyperledger/crypto/peerAdminTeam'
            - './crypto-config/peerOrganizations/Manufacturer.liquor.com/peers/peer0.Manufacturer.liquor.com/:/etc/hyperledger/crypto/peerManufacturer'
            
#            - './orderer1.liquor.com:/var/hyperledger/production/orderer'

    orderer2.liquor.com:
        container_name: orderer2.liquor.com
        image: 'hyperledger/fabric-orderer:1.4.3'
        environment:
            - ORDERER_GENERAL_LOGLEVEL=debug
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerAdminTeam/tls/ca.crt, /etc/hyperledger/crypto/peerManufacturer/tls/ca.crt] 
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
        command: orderer
        ports:
            - '9050:7050'
        volumes:
            - '../artifacts:/etc/hyperledger/configtx'
            - './crypto-config/ordererOrganizations/liquor.com/orderers/orderer2.liquor.com/:/etc/hyperledger/crypto/orderer'
            - './crypto-config/peerOrganizations/AdminTeam.liquor.com/peers/peer0.AdminTeam.liquor.com/:/etc/hyperledger/crypto/peerAdminTeam'
            - './crypto-config/peerOrganizations/Manufacturer.liquor.com/peers/peer0.Manufacturer.liquor.com/:/etc/hyperledger/crypto/peerManufacturer'
#            - './orderer2.liquor.com:/var/hyperledger/production/orderer'
           
            
    orderer3.liquor.com:
        container_name: orderer3.liquor.com
        image: 'hyperledger/fabric-orderer:1.4.3'
        environment:
            - ORDERER_GENERAL_LOGLEVEL=debug
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerAdminTeam/tls/ca.crt, /etc/hyperledger/crypto/peerManufacturer/tls/ca.crt]
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
        command: orderer
        ports:
            - '10050:7050'
        volumes:
            - '../artifacts:/etc/hyperledger/configtx'
            - './crypto-config/ordererOrganizations/liquor.com/orderers/orderer3.liquor.com/:/etc/hyperledger/crypto/orderer'
            - './crypto-config/peerOrganizations/AdminTeam.liquor.com/peers/peer0.AdminTeam.liquor.com/:/etc/hyperledger/crypto/peerAdminTeam'
            - './crypto-config/peerOrganizations/Manufacturer.liquor.com/peers/peer0.Manufacturer.liquor.com/:/etc/hyperledger/crypto/peerManufacturer'
#            - './orderer3.liquor.com:/var/hyperledger/production/orderer'
            
    orderer4.liquor.com:
        container_name: orderer4.liquor.com
        image: 'hyperledger/fabric-orderer:1.4.3'
        environment:
            - ORDERER_GENERAL_LOGLEVEL=debug
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerAdminTeam/tls/ca.crt, /etc/hyperledger/crypto/peerManufacturer/tls/ca.crt]
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
        command: orderer
        ports:
            - '11050:7050'
        volumes:
            - '../artifacts:/etc/hyperledger/configtx'
            - './crypto-config/ordererOrganizations/liquor.com/orderers/orderer4.liquor.com/:/etc/hyperledger/crypto/orderer'
            - './crypto-config/peerOrganizations/AdminTeam.liquor.com/peers/peer0.AdminTeam.liquor.com/:/etc/hyperledger/crypto/peerAdminTeam'
            - './crypto-config/peerOrganizations/Manufacturer.liquor.com/peers/peer0.Manufacturer.liquor.com/:/etc/hyperledger/crypto/peerManufacturer'
            
#            - './orderer4.liquor.com:/var/hyperledger/production/orderer'


    couchdb.peer0.AdminTeam:
        container_name: couchdb.peer0.AdminTeam
        image: 'hyperledger/fabric-couchdb:0.4.18'
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        ports:
            - '13050:5984'
    peer0.AdminTeam.liquor.com:
        container_name: peer0.AdminTeam.liquor.com
        extends:
            file: base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.AdminTeam.liquor.com
            - CORE_PEER_LOCALMSPID=AdminTeamMSP
            - CORE_PEER_ADDRESS=peer0.AdminTeam.liquor.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.AdminTeam:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.AdminTeam.liquor.com:7051            
        ports:
            - '7051:7051'
            - '7053:7053'
        volumes:
            - './crypto-config/peerOrganizations/AdminTeam.liquor.com/peers/peer0.AdminTeam.liquor.com/:/etc/hyperledger/crypto/peer'
#           - './peer0.AdminTeam.liquor.com:/var/hyperledger/production'
        depends_on:
            - couchdb.peer0.AdminTeam
            - orderer.liquor.com

    couchdb.peer0.Manufacturer:
        container_name: couchdb.peer0.Manufacturer
        image: 'hyperledger/fabric-couchdb:0.4.18'
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        ports:
            - '20050:5984'
    peer0.Manufacturer.liquor.com:
        container_name: peer0.Manufacturer.liquor.com
        extends:
            file: base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.Manufacturer.liquor.com
            - CORE_PEER_LOCALMSPID=ManufacturerMSP
            - CORE_PEER_ADDRESS=peer0.Manufacturer.liquor.com:7056
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.Manufacturer:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Manufacturer.liquor.com:7056
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7056  
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7057
        ports:
            - '7056:7056'
            - '7058:7058'
        volumes:
            - ./crypto-config/peerOrganizations/Manufacturer.liquor.com/peers/peer0.Manufacturer.liquor.com/:/etc/hyperledger/crypto/peer
#            - './peer0.Manufacturer.liquor.com:/var/hyperledger/production'           
        depends_on:
            - couchdb.peer0.Manufacturer
            - orderer.liquor.com

    
    cli:
        container_name: cli
        image: hyperledger/fabric-tools
        tty: true
        environment:
            - GOPATH=/etc/hyperledger/fabric/peer
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=peer0.AdminTeam.liquor.com
            - CORE_PEER_LOCALMSPID=AdminTeamMSP
            - CORE_PEER_ADDRESS=peer0.AdminTeam.liquor.com:7051
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/AdminTeam.liquor.com/peers/peer0.AdminTeam.liquor.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/AdminTeam.liquor.com/peers/peer0.AdminTeam.liquor.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/AdminTeam.liquor.com/peers/peer0.AdminTeam.liquor.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/AdminTeam.liquor.com/users/Admin@AdminTeam.liquor.com/msp
        working_dir: /etc/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
#            - ./src/:/etc/hyperledger/fabric/peer/src
            - ../scripts:/etc/hyperledger/fabric/peer/scripts/
            - ../artifacts:/etc/hyperledger/fabric/peer/artifacts
            - ./crypto-config:/etc/hyperledger/fabric/peer/crypto/
            - ../artifacts:/etc/hyperledger/configtx
        ports:
            - '9092'
        depends_on:
            - orderer.liquor.com
            - peer0.AdminTeam.liquor.com            
   
