---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "prime-hyperledgerfabric-setup"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "prime Artwork Network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see Bank1.yaml and org2.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  primechannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.prime.com
      - orderer1.prime.com
      - orderer2.prime.com
      - orderer3.prime.com
      - orderer4.prime.com

    # Required. list of peers from participating orgs
    peers:
      peer0.Student.prime.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer0.AdminTeam.prime.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.Employer.prime.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.University.prime.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - mycc:v0
#
# list of participating organizations in this network
#
organizations:
  Student:
    mspid: StudentMSP

    peers:
      - peer0.Student.prime.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca-Student

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/Student.prime.com/users/Admin@Student.prime.com/msp/keystore/ddff913527944538a615fd3bedf322f6249b1b13b6984a96527b7b72575d7a39_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/Student.prime.com/users/Admin@Student.prime.com/msp/signcerts/Admin@Student.prime.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  AdminTeam:
    mspid: AdminTeamMSP
    peers:
      - peer0.AdminTeam.prime.com


    certificateAuthorities:
      - ca-AdminTeam
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/AdminTeam.prime.com/users/Admin@AdminTeam.prime.com/msp/keystore/e2c787c47c25f00f7cc0deafdcd41751ed0565bc8bd0a1c10c382d4298d4dff6_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/AdminTeam.prime.com/users/Admin@AdminTeam.prime.com/msp/signcerts/Admin@AdminTeam.prime.com-cert.pem


  Employer:
    mspid: EmployerMSP
    peers:
      - peer0.Employer.prime.com
    certificateAuthorities:
      - ca-Employer
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/Employer.prime.com/users/Admin@Employer.prime.com/msp/keystore/203df477721957d0ce028491d4f77038ee4f7fcfa41b495df9aa47bdfb838395_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/Employer.prime.com/users/Admin@Employer.prime.com/msp/signcerts/Admin@Employer.prime.com-cert.pem


  University:
    mspid: UniversityMSP
    peers:
      - peer0.University.prime.com
    certificateAuthorities:
      - ca-University
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/University.prime.com/users/Admin@University.prime.com/msp/keystore/6d1b8b6fb01ef48b14d5393ff8d1a8ef9a594c0ddcd6adaf723a92f4123cfa71_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/University.prime.com/users/Admin@University.prime.com/msp/signcerts/Admin@University.prime.com-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#

orderers:
  orderer.prime.com:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.prime.com

    tlsCACerts:
      path: artifacts/channel/crypto-config/ordererOrganizations/prime.com/orderers/orderer.prime.com/tls/ca.crt

  

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:

  peer0.Student.prime.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:9351

    grpcOptions:
      ssl-target-name-override: peer0.Student.prime.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/Student.prime.com/peers/peer0.Student.prime.com/tls/ca.crt
    

  peer0.AdminTeam.prime.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer0.AdminTeam.prime.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/AdminTeam.prime.com/peers/peer0.AdminTeam.prime.com/tls/ca.crt
    



  peer0.Employer.prime.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7056

    grpcOptions:
      ssl-target-name-override: peer0.Employer.prime.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/Employer.prime.com/peers/peer0.Employer.prime.com/tls/ca.crt



  peer0.University.prime.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:9251

    grpcOptions:
      ssl-target-name-override: peer0.University.prime.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/University.prime.com/peers/peer0.University.prime.com/tls/ca.crt
  

 

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-Student:
    url: https://localhost:7354
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/Student.prime.com/ca/ca.Student.prime.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-Student

  ca-AdminTeam:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/AdminTeam.prime.com/ca/ca.AdminTeam.prime.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-AdminTeam

  ca-Employer:
    url: https://localhost:7154
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/Employer.prime.com/ca/ca.Employer.prime.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-Employer

  ca-University:
    url: https://localhost:7254
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/University.prime.com/ca/ca.University.prime.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-University

  
